# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
# relative_permalinks: true

# Setup
title:               Baltimoreâ€™s Civil Rights Heritage
tagline:             'Looking for Landmarks from the Movement'
description:         'This site is a repository for writing, data and resources related to the African-American Civil Rights movement in Baltimore. This is a project of <a href="http://baltimoreheritage.org/">Baltimore Heritage</a> and our partners.'
url:                 http://baltimoreheritage.github.io/civil-rights-heritage
baseurl:             '/civil-rights-heritage'
paginate:            5

# About/contact
author:
  name:              Baltimore Heritage
  url:               http://baltimoreheritage.org
  email:             info@baltimoreheritage.org

# Google Analytics

ga_tracking_code: UA-16215864-7

# Required Gems

gems:
  - jekyll-redirect-from # Redirection https://help.github.com/articles/redirects-on-github-pages/
  - jekyll-paginate
